from django.urls import path
from . import views


urlpatterns = [
      path('', views.home, name='home'),
      path('test_chef/', views.test_chef, name='test_chef'),
      path('nouvelle_demande/', views.nouvelle_demande, name='nouvelle_demande'),
      path('mes_demandes/', views.mes_demandes, name='mes_demandes' ),
      path('demandes_a_valider/', views.demandes_a_valider, name='demandes_a_valider' ),
      path('valider_demande/<int:demande_id>/', views.valider_demande, name='valider_demande'),
      path('demandes_remplacent/', views.demandes_remplacent, name='demandes_remplacent'),
      path('accepter_remplacent/<int:demande_id>/', views.accepter_remplacent, name='accepter_remplacent'),
      path('detail_demande/<int:demande_id>/', views.detail_demande, name='detail_demande'),
      path('recherche_demandes/', views.recherche_demandes, name='recherche_demandes'),
      path('gerer_employes/', views.gerer_employes, name='gerer_employes'),
      path('rapport_solde_historique/', views.rapport_solde_historique, name='rapport_solde_historique'),
      path('rapport_absences/', views.rapport_absences_form, name='rapport_absences_form'),
      path('rapport_absences_pdf/', views.rapport_absences_departement, name='rapport_absences_departement'),
      path('missions/', views.mission_liste, name='mission_liste'),
      path('missions/creer/', views.mission_creer, name='mission_creer'),
      path('missions/<int:mission_id>/corriger/', views.mission_corriger, name='mission_corriger'),
      path('dashboard/', views.dashboard, name='dashboard'),
      path('missions/<int:mission_id>/supprimer/', views.mission_supprimer, name='mission_supprimer'),
      path('nouvelle_demande/<int:demande_id>/', views.nouvelle_demande, name='modifier_demande'),
      path('employes/', views.liste_employes, name='liste_employes'),
      path('employes/<int:employe_id>/modifier/', views.modifier_employe_role, name='modifier_employe_role'),
      path('employes/<int:employe_id>/supprimer/', views.supprimer_employe, name='supprimer_employe'),
      path('demandes_validees/', views.demandes_validees, name='demandes_validees'),
      path('gerer_direction/', views.gerer_direction, name='gerer_direction'),
      path('gerer_departement/', views.gerer_departement, name='gerer_departement'),
      path('gerer_groupe/', views.gerer_groupe, name='gerer_groupe'),
      path('gerer_direction/<int:pk>/modifier/', views.modifier_direction, name='modifier_direction'),
      path('gerer_direction/<int:pk>/supprimer/', views.supprimer_direction, name='supprimer_direction'),
      path('gerer_departement/<int:pk>/modifier/', views.modifier_departement, name='modifier_departement'),
      path('gerer_departement/<int:pk>/supprimer/', views.supprimer_departement, name='supprimer_departement'),
      path('gerer_groupe/<int:pk>/modifier/', views.modifier_groupe, name='modifier_groupe'),
      path('gerer_groupe/<int:pk>/supprimer/', views.supprimer_groupe, name='supprimer_groupe'),
      path('notifications/<int:notification_id>/', views.notification_click, name='notification_click'),
]