# Generated by Django 6.0.7 on 2026-08-03 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('fonction', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ES', 'Employé Simple'), ('CG', 'Chef de Groupe'), ('CD', 'Chef de Département'), ('DIR', 'Directeur')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directeur', to='conges.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Depratement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep', to='conges.direction')),
                ('Chef_de_departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_de_departemenet', to='conges.employe')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('dateDebut', models.DateTimeField()),
                ('dateFin', models.DateTimeField()),
                ('Numbrejours', models.DecimalField(decimal_places=0, max_digits=2)),
                ('piece_Joine', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('commentaire', models.TextField(blank=True)),
                ('statue', models.CharField(choices=[('VA', 'Validé'), ('REF', 'Refusé'), ('EN ATT', 'En attente'), ('BR', 'Brouillon')], max_length=10)),
                ('motif', models.CharField(max_length=255)),
                ('type_conge', models.CharField(choices=[('1', 'Congé xxx'), ('2', 'Congé maladie'), ('3', 'Congé xx'), ('AU', 'Autre')], max_length=10)),
                ('name_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe', to='conges.employe')),
                ('name_remplacent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remplacent', to='conges.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chef_de_groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_de_groupe', to='conges.employe')),
                ('depratement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupe', to='conges.depratement')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='conges.demandeconge')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='conges.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('type_notif', models.CharField(choices=[('UPD', 'Update'), ('DMD', 'Demande')], max_length=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='conges.employe')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe_roles', to='conges.depratement')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe_roles', to='conges.direction')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='conges.employe')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe_roles', to='conges.groupe')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_role', to='conges.role')),
            ],
        ),
        migrations.CreateModel(
            name='Solde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_annuel', models.DecimalField(decimal_places=2, max_digits=6)),
                ('solde_recuperation', models.DecimalField(decimal_places=2, max_digits=6)),
                ('solde_consomme', models.DecimalField(decimal_places=2, max_digits=6)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde', to='conges.employe')),
            ],
        ),
    ]
