# Generated by Django 6.0.7 on 2026-08-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depratement',
            name='nom_de_departement',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direction',
            name='nom_de_direction',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupe',
            name='nom_de_groupe',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
