# Generated by Django 6.0.7 on 2026-08-03 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0002_depratement_nom_de_departement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandeconge',
            name='dateCreation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='demandeconge',
            name='dateDebut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='demandeconge',
            name='dateFin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='demandeconge',
            name='motif',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historique',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
