# Generated by Django 6.0.7 on 2026-08-10 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0003_employe_user_alter_demandeconge_datecreation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='niveau_validation',
            field=models.CharField(blank=True, choices=[('CG', 'Chef de Groupe'), ('CD', 'Chef de Département'), ('DIR', 'Directeur')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='demandeconge',
            name='statue',
            field=models.CharField(choices=[('VA', 'Validé'), ('REF', 'Refusé'), ('EN_ATT_RMP', 'En attente remplacent'), ('EN_ATT_VA', 'En attente validation'), ('BR', 'Brouillon'), ('ANN', 'Annulé')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employerole',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='conges.employe'),
        ),
    ]
