# Generated by Django 6.0.7 on 2026-08-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0004_demandeconge_niveau_validation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ES', 'Employé Simple'), ('CG', 'Chef de Groupe'), ('CD', 'Chef de Département'), ('DIR', 'Directeur'), ('DRH', 'DRH')], max_length=20, unique=True),
        ),
    ]
