# Generated by Django 6.0.7 on 2026-08-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0005_alter_role_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depratement',
            new_name='Departement',
        ),
    ]
