# Generated by Django 6.0.7 on 2026-08-12 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0006_rename_depratement_departement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('jours_recuperation', models.IntegerField(blank=True, default=0)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='conges.employe')),
            ],
        ),
    ]
