# Generated by Django 6.0.7 on 2026-08-14 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0007_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='conges.demandeconge'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='conges.employe'),
        ),
    ]
