# Generated by Django 6.0.7 on 2026-08-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0008_notification_demande_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
