# Generated by Django 6.0.7 on 2026-08-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0009_notification_lu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
