# Generated by Django 6.0.7 on 2026-08-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0010_alter_notification_datecreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solde',
            name='solde_annuel',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='solde',
            name='solde_consomme',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='solde',
            name='solde_recuperation',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
