# Generated by Django 6.0.7 on 2026-08-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0011_alter_solde_solde_annuel_alter_solde_solde_consomme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='commentaire',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historique',
            name='decision',
            field=models.CharField(choices=[('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historique',
            name='type_action',
            field=models.CharField(choices=[('VALIDATION', 'Validation de congé'), ('REMPLACEMENT', 'Remplacement')], default='VALIDATION', max_length=20),
            preserve_default=False,
        ),
    ]
