# Generated by Django 6.0.7 on 2026-08-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0012_historique_commentaire_historique_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solde',
            name='jours_consommes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
